export const enum Operacao {
  DEBITO = 'DEBITO',

  CREDITO1X = 'CREDITO1X',

  CREDITO2X = 'CREDITO2X',

  CREDITO3X = 'CREDITO3X',

  CREDITO4X = 'CREDITO4X',

  CREDITO5X = 'CREDITO5X',

  CREDITO6X = 'CREDITO6X',

  CREDITO7X = 'CREDITO7X',

  CREDITO8X = 'CREDITO8X',

  CREDITO9X = 'CREDITO9X',

  CREDITO10X = 'CREDITO10X',

  CREDITO11X = 'CREDITO11X',

  CREDITO12X = 'CREDITO12X',
}
